### ISSUE TITLE
--shared-memory is disallowed because it was not compiled with 'atomics' or 'bulk-memory' features.

### ISSUE THREAD

**Issue by aihornmac** [donalffons/opencascade.js#103]
Thx so much for your work on this lib! It helped a lot!

Now I wanna go further with multi threading, so I tried to build from docker. Unfortunately it failed.

I was hoping that you could shed some light on it.

Here is the error message:

```
wasm-ld: error: --shared-memory is disallowed by /opencascade.js/build/bindings/BRepTools/BRepTools.hxx/BRepTools.cpp.o because it was not compiled with 'atomics' or 'bulk-memory' features.
emcc: error: '/emsdk/upstream/bin/wasm-ld @/tmp/emscripten_8un2px8q.rsp.utf-8' failed (returned 1)
```
Full file see: [error.log](https://github.com/donalffons/opencascade.js/files/8383473/error.log)

Here is the command I ran:

```bash
docker run --rm -e threading=multi-threaded -it -v $(pwd):/src -u $(id -u):$(id -g) donalffons/opencascade.js build/occ.yaml
```

with following yaml file:

```yaml
  mainBuild:
    name: rocketExample.js
    bindings:
      # - symbol: STEPCAFControl_Reader
      # - symbol: IFSelect_ReturnStatus
      # - symbol: TCollection_ExtendedString
      # - symbol: TDocStd_Document
      # - symbol: Handle_TDocStd_Document
      - symbol: Message_ProgressRange
      # - symbol: XCAFDoc_DocumentTool
      # - symbol: TDF_LabelSequence
      # - symbol: XCAFDoc_ShapeTool
      # - symbol: TCollection_AsciiString
      # - symbol: RWGltf_CafWriter
      - symbol: BRepTools
      - symbol: BRepMesh_IncrementalMesh
      # - symbol: TColStd_IndexedDataMapOfStringString
      # - symbol: CDM_Document
      # - symbol: Standard_Transient
      # - symbol: TDF_Label
      # - symbol: TDataStd_GenericEmpty
      # - symbol: TDF_Attribute
      # - symbol: Handle_XCAFDoc_ShapeTool
      # - symbol: NCollection_BaseSequence
      - symbol: TopoDS_Shape
      # - symbol: BRepMesh_DiscretRoot
      # - symbol: NCollection_BaseMap

      - symbol: CustomClass
    emccFlags:
      # @see https://github.com/emscripten-core/emscripten/blob/main/src/settings.js
      - -O3
      - -sEXPORT_ES6=1
      - -sUSE_ES6_IMPORT_META=0
      - -sEXPORTED_RUNTIME_METHODS=['FS']
      - -sINITIAL_MEMORY=100MB
      - -sMAXIMUM_MEMORY=4GB
      - -sALLOW_MEMORY_GROWTH=1
      - -sUSE_FREETYPE=1
      # - -sWASM_WORKERS=1
      # - -pthread
      # - -sPTHREAD_POOL_SIZE='navigator.hardwareConcurrency'
      # - -sOFFSCREENCANVAS_SUPPORT=1
  additionalCppCode: |
    #include <iostream>
    class CustomClass {
    public:
      static void SayHello() {
        std::cout << "Hello, World" << std::endl;
      }
    };
```
