### ISSUE TITLE
Cannot call BRep_Tool.Triangulation due to unbound types: N11opencascade6handleI18Poly_TriangulationEE

### ISSUE THREAD

**Issue by flolu** [donalffons/opencascade.js#154]
I'm using the following code from [openCascadeHelper.js](https://github.com/donalffons/opencascade.js-examples/blob/e675ed7ea9287356df23e2fda496cfe735f86f23/src/common/openCascadeHelper.js#L17)

```typescript
const myFace = oc.TopoDS.Face_1(ExpFace.Current())
const aLocation = new oc.TopLoc_Location_1()
const myT = oc.BRep_Tool.Triangulation(myFace, aLocation, 0 /* == Poly_MeshPurpose_NONE */)
```

But the third line throws the following error:

```
UnboundTypeError: Cannot call BRep_Tool.Triangulation due to unbound types: N11opencascade6handleI18Poly_TriangulationEE
```

**Which bindings am I missing?** Is there a list of all available bindings? Note: the code works fine with the full build.

This is my current custom build file:
```yaml
mainBuild:
  name: customBuild.examples.js
  bindings:
    - symbol: BRepTools
    - symbol: NCollection_BaseSequence
    - symbol: TDataStd_GenericEmpty
    - symbol: TDF_Attribute
    - symbol: TDF_LabelSequence
    - symbol: XSControl_Reader
    - symbol: STEPControl_Reader
    - symbol: IFSelect_ReturnStatus
    - symbol: RWGltf_CafWriter
    - symbol: TCollection_AsciiString
    - symbol: Handle_TDocStd_Document
    - symbol: TDocStd_Document
    - symbol: TColStd_IndexedDataMapOfStringString
    - symbol: Message_ProgressRange
    - symbol: XCAFDoc_DocumentTool
    - symbol: XCAFDoc_ShapeTool
    - symbol: BRepMesh_IncrementalMesh
    - symbol: TopoDS_Shape
    - symbol: Handle_XCAFDoc_ShapeTool
    - symbol: STEPCAFControl_Reader
    - symbol: NCollection_BaseMap
    - symbol: TDF_Label
    - symbol: BRepMesh_DiscretRoot
    - symbol: TCollection_ExtendedString
    - symbol: CDM_Document
    - symbol: Standard_Transient
    - symbol: TopExp_Explorer
    - symbol: TopAbs_ShapeEnum
    - symbol: TopoDS_Compound
    - symbol: TopoDS_Face
    - symbol: TopoDS_Builder
    - symbol: TopoDS_Edge
    - symbol: TopoDS_Wire
    - symbol: TopoDS
    - symbol: TopoDS_Iterator
    - symbol: TopLoc_Location
    - symbol: Poly_Connect
    - symbol: BRep_Tool
    - symbol: TColgp_Array1OfDir
    - symbol: StdPrs_ToolTriangulatedShape
    - symbol: Poly_Triangulation
    - symbol: RWMesh_TriangulationSource
  emccFlags:
    - -flto
    - -fexceptions
    - -sDISABLE_EXCEPTION_CATCHING=1
    - -O3
    - -sEXPORT_ES6=1
    - -sUSE_ES6_IMPORT_META=0
    - -sEXPORTED_RUNTIME_METHODS=['FS']
    - -sINITIAL_MEMORY=15MB
    - -sMAXIMUM_MEMORY=4GB
    - -sALLOW_MEMORY_GROWTH=1
    - -sLLD_REPORT_UNDEFINED
    - --no-entry
    - -sENVIRONMENT='web'
```
