### ISSUE TITLE
Custom Build: XCAFDoc_DocumentTool.ShapeTool is not a function

### ISSUE THREAD

**Issue by stefanFuess** [donalffons/opencascade.js#234]
I made a custom Build 

````
mainBuild:
  name: opencascade.full.js
  bindings:
    - symbol: gp_Trsf
    - symbol: gp_Vec
    - symbol: gp_Quaternion
    - symbol: BRepBuilderAPI_Transform
    - symbol: STEPControl_Writer
    - symbol: Message_ProgressRange
    - symbol: TopoDS_Shape
    - symbol: TopoDS_Compound
    - symbol: BRep_Builder
    - symbol: TopoDS_Builder
    - symbol: STEPControl_Reader
    - symbol: XSControl_Reader
    - symbol: IFSelect_ReturnStatus
    - symbol: BRepBuilderAPI_ModifyShape
    - symbol: BRepBuilderAPI_MakeShape
    - symbol: BRepBuilderAPI_Command
    - symbol: STEPControl_StepModelType
    - symbol: TCollection_ExtendedString
    - symbol: TDocStd_Document 
    - symbol: CDM_Document
    - symbol: Standard_Transient
    - symbol: Handle_TDocStd_Document
    - symbol: XCAFDoc_DocumentTool
    - symbol: TDF_Label
    
    - symbol: CustomClass
  emccFlags:
    - -O3
    - -sEXPORT_ES6=1
    - -sUSE_ES6_IMPORT_META=0
    - -sEXPORTED_RUNTIME_METHODS=['FS']
    - -sINITIAL_MEMORY=100MB
    - -sMAXIMUM_MEMORY=4GB
    - -sALLOW_MEMORY_GROWTH=1
    - -sUSE_FREETYPE=1
additionalCppCode: |
  #include <iostream>
  class CustomClass {
  public:
    static void SayHello() {
      std::cout << "Hello, World" << std::endl;
    }
  };
````

The build completes, but I get an type error:

`TypeError: openCascade.XCAFDoc_DocumentTool.ShapeTool is not a function`

which I dont get with the full build.
