### ISSUE TITLE
Custom build with custom C++ classes

### ISSUE THREAD

**Issue by mnesarco** [donalffons/opencascade.js#35]
First of all, thank you for this project.

Is it possible to use the docker container to create a custom build including some own c++ code?  I have created a c++ library using opencascade and I want to compile it to wasm using your opecascade port. But I don't see how to include my code in the custom build.

I don't need to expose anything from OpenCascade directly to javascript, I just need to expose some own c++ classes that uses openccascade internally, but I know very few about wasm/Emscripten. I suppose that if there is a way to inject my own code into the process, the custom build can build everything together and expose my classes as any other OCC class.

Thank you.

**Comment by donalffons** [comment]
Hi!

> Is it possible to use the docker container to create a custom build including some own c++ code? I have created a c++ library using opencascade and I want to compile it to wasm using your opecascade port. But I don't see how to include my code in the custom build.

Hmm, that is an interesting use case, but not really something that is "supported" at the moment. Here are some ideas, though:

- Generally, you would probably have the best chances of success if your custom API follows the layout of the OpenCascade API, i.e. everything should be wrapped inside classes, no functions inside the global scope. You might also want to try to use a naming scheme, similar to OpenCascade...
- You might want treat your custom API as an OpenCascade "package" (i.e. similar to `math` or `gp`etc.). You should have all your source and header files inside a folder (no sub-folders) named `myApi`, for example.
- During the build process, a [Docker container](https://github.com/donalffons/opencascade.js/blob/master/Dockerfile#L114) is created which has the OpenCascade sources saved in `/occt/occt-94c0055/src`. You might be able to put your custom API in its own folder at this location using a `COPY myApi /occt/occt-94c0055/src` command inside the Dockerfile.
- You can create a custom build of the library ([doc](https://github.com/donalffons/opencascade.js/blob/master/doc/README.md#creating-a-custom-build), [example](https://github.com/donalffons/opencascade.js/blob/master/src/builds/customBuild.yml)). As your YAML file, you could use something like this
```yml
myApi.js:
  bindings:
    - package: "myApi"
    - module: "TKernel"
    - module: "TKMath"
    - module: "TKG2d"
    - module: "TKG3d"
    - module: "..." # Include all the modules you need
  
  emccFlags:
    - -sEXPORT_ES6=1
    - -sUSE_ES6_IMPORT_META=0
    - -sEXTRA_EXPORTED_RUNTIME_METHODS=["FS"]
    - -O3
    - -sAGGRESSIVE_VARIABLE_ELIMINATION=1
```
